import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NavBar, SideBar } from "@/components";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} overscroll-none antialiased`}
      >
        <ThemeProvider attribute='class'
          defaultTheme='dark'
          themes={['light', 'dark']}>
          <NavBar />
          <div className="min-h-[var(--screen-minus-navbar)] flex md:gap-4 transition-all duration-300">
            <SideBar />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
